# Generated by Django 2.1.5 on 2025-04-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_process', models.TextField(blank=True, null=True)),
                ('user_requirements', models.TextField(blank=True, null=True)),
                ('non_functional_requirements', models.TextField(blank=True, null=True)),
                ('user_roles_permissions', models.TextField(blank=True, null=True)),
                ('system_integration', models.TextField(blank=True, null=True)),
                ('technical_architecture', models.TextField(blank=True, null=True)),
                ('data_management', models.TextField(blank=True, null=True)),
                ('ui_interaction_design', models.TextField(blank=True, null=True)),
                ('security_compliance', models.TextField(blank=True, null=True)),
                ('acceptance_criteria', models.TextField(blank=True, null=True)),
                ('project_budget', models.TextField(blank=True, null=True)),
                ('project_timeline', models.TextField(blank=True, null=True)),
                ('risk_management', models.TextField(blank=True, null=True)),
                ('post_deployment_support', models.TextField(blank=True, null=True)),
                ('legal_compliance', models.TextField(blank=True, null=True)),
                ('extra_information', models.TextField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
