# Generated by Django 2.1.5 on 2025-05-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectedinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.CharField(default='2025-06-01', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.CharField(default='2025-06-01', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.CharField(default='good', max_length=180),
            preserve_default=False,
        ),
    ]
