# Generated by Django 2.1.5 on 2025-05-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20250517_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plannerid', models.CharField(blank=True, max_length=100, null=True)),
                ('teams_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
