name: fyp_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.9.21
  - pip=25.0
  - openssl=3.0.15
  - ca-certificates=2024.12.31
  - sqlite=3.45.3
  - setuptools=75.8.0
  # - vc=14.42 # [win]
  # - vs2015_runtime=14.42.34433 # [win]
  - wheel=0.45.1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.8.0
      - asgiref==3.8.1
      - backports-zoneinfo==0.2.1
      - blinker==1.8.2
      - boto3==1.34.52
      - botocore==1.34.52
      - certifi==2025.1.31
      - charset-normalizer==3.4.2
      - click==8.1.8
      - colorama==0.4.6
      - distro==1.9.0
      - dj-database-url==0.5.0
      - dj-static==0.0.6
      - django==4.2.0
      - django-appconf==1.0.2
      - django-multiselectfield==0.1.8
      - django-staticfiles==1.2.1
      - django-storages==1.6.6
      - djangorestframework==3.15.2
      - docutils==0.14
      - drf-yasg==1.21.8
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - flask==3.0.3
      - gunicorn==19.7.1
      - h11==0.14.0
      - httpcore==1.0.8
      - httpx==0.28.1
      - idna==3.10
      - importlib-metadata==8.5.0
      - inflection==0.5.1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.9.0
      - jmespath==0.9.3
      - joblib==1.4.2
      - markupsafe==2.1.5
      - nltk==3.9.1
      - numpy==1.24.4
      - openai==1.60.2
      - openpyxl==3.1.5
      - packaging==24.2
      - pandas==2.2.3
      - pillow==8.2.0
      - psycopg2-binary==2.9.9
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pypdf==5.5.0
      - python-dateutil==2.8.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - python-dotenv==1.0.1
      - regex==2024.11.6
      - requests==2.32.3
      - six==1.11.0
      - sniffio==1.3.1
      - sqlparse==0.5.3
      - static3==0.7.0
      - tqdm==4.67.1
      - typing-extensions==4.13.1
      - tzdata==2025.2
      - uritemplate==4.1.1
      - urllib3==1.25.4
      - watchdog==4.0.2
      - werkzeug==3.0.6
      - zipp==3.20.2
      - chromadb==0.6.3
      - langchain==0.3.17
      - langchain_chroma==0.2.1
      - langchain_community==0.3.16
      - langchain_huggingface==0.1.2
      - sentence-transformers==3.4.1
